# Generated by Django 5.2.1 on 2025-05-31 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian điểm danh')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
        ),
    ]
